from __future__ import annotations

import re

from malca.ltv.multi_survey import LTV_MS_FEATURE_COLUMN_SPECS
from malca.vsx.filter import EXCLUDE as VSX_EXCLUDE_CLASSES
from malca.vsx.filter import tokenize_classes as tokenize_vsx_classes


SPECIAL_FILTERS = {
    "only_unreviewed": "Only unreviewed",
    "require_failed_any_false": "Require failed_any=False",
}

# Catalog/type filters controlled by the vetting known-type presets.
# The broad preset uses all of them; the "certain known" preset leaves
# vetting_likely_known unset and drops uncertainty-style categorical labels.
VETTING_KNOWN_BOOL_FILTERS = (
    "vetting_likely_known",
    "microlens_match",
)

VETTING_KNOWN_SELECT_FILTERS = (
    "vsx_class",
    "microlens_catalog",
    "asassn_var_type",
    "gaia_var_class",
    "simbad_otype",
    "ztf_var_type",
    "tns_type",
    "alerce_lc_class",
)

REVIEW_TAXONOMY_FILTER_COLUMNS: tuple[tuple[str, str], ...] = (
    ("select", "workflow_status"),
    ("num", "interest_score"),
    ("num", "review_pass"),
    ("select", "disposition"),
    ("select", "morphology_primary"),
    ("select", "morphology_secondary"),
    ("select", "morphology_polarity"),
    ("select", "morphology_recurrence"),
    ("select", "baseline_behavior"),
    ("select", "physical_primary"),
    ("select", "physical_secondary"),
    ("select", "classification_confidence"),
    ("text", "reviewer"),
    ("text", "duplicate_of"),
    ("text", "known_object_id"),
    ("text", "known_object_source"),
    ("num", "taxonomy_version"),
)

REVIEW_FILTER_COLUMN_TYPES = {
    col: kind for kind, col in REVIEW_TAXONOMY_FILTER_COLUMNS
}

_VSX_GENERIC_CLASSES = {"*", "MISC", "NAN", "NONE", "VAR"}
_ASASSN_GENERIC_CLASSES = {"VAR"}
_SIMBAD_GENERIC_TYPES = {"*", "**", "G", "FIR", "MUL"}
_TNS_UNCERTAIN_RE = re.compile(
    r"(?:^|[\s_\-/(,.;:])(?:candidate|possible|probable|probably|suspected|tentative|uncertain)"
    r"(?:$|[\s_\-/),.;:])",
    re.IGNORECASE,
)
_TNS_DEFINITE_SN_RE = re.compile(r"^(?:sn|supernova)\b", re.IGNORECASE)


def _normalized_class_value(value: object) -> str:
    return str(value or "").strip()


def _is_tns_definite_type(text: str) -> bool:
    lowered = text.lower()
    if "?" in text:
        return False
    if _TNS_UNCERTAIN_RE.search(text):
        return False
    if _TNS_DEFINITE_SN_RE.search(text):
        return True
    if lowered in {"cv", "cataclysmic variable", "nova", "classical nova", "tde"}:
        return True
    if lowered.startswith("tidal disruption"):
        return True
    return False


def _is_vsx_definite_known_type(text: str) -> bool:
    """Return whether a VSX label contains a known-type contaminant token."""
    if text.upper() in _VSX_GENERIC_CLASSES:
        return False
    if ":" in text:
        return False
    tokens = set(tokenize_vsx_classes(text))
    if not tokens or tokens <= _VSX_GENERIC_CLASSES:
        return False
    return bool(tokens & VSX_EXCLUDE_CLASSES)


def is_definite_known_type_value(column: str, value: object) -> bool:
    """Return whether a catalog class value is a definite known-type exclusion."""
    text = _normalized_class_value(value)
    if not text:
        return False

    col = str(column or "").strip()
    upper = text.upper()

    if col == "vsx_class":
        return _is_vsx_definite_known_type(text)
    if col == "asassn_var_type":
        return ":" not in text and upper not in _ASASSN_GENERIC_CLASSES
    if col == "simbad_otype":
        return "?" not in text and upper not in _SIMBAD_GENERIC_TYPES
    if col == "tns_type":
        return _is_tns_definite_type(text)
    if col in {"gaia_var_class", "ztf_var_type", "alerce_lc_class", "microlens_catalog"}:
        return True

    return True


SIDEBAR_GROUPS = [
    ("Review Taxonomy", list(REVIEW_TAXONOMY_FILTER_COLUMNS)),
    ("Vetting", [
        ("bool", "vetting_likely_known"),
        ("bool", "microlens_match"),
        ("num", "pm_cluster_offset_sigma"),
        ("num", "pm_total"),
        ("bool", "high_pm_flag"),
        ("select", "vsx_class"),
        ("select", "microlens_catalog"),
        ("select", "asassn_var_type"),
        ("select", "gaia_var_class"),
        ("select", "simbad_otype"),
        ("select", "ztf_var_type"),
        ("select", "tns_type"),
        ("select", "alerce_lc_class"),
        ("select", "yso_class"),
        ("text", "catalog_source"),
        ("text", "asassn_var_name"),
        ("num", "asassn_var_period"),
        ("num", "vsx_period"),
        ("num", "vsx_sep_arcsec"),
        ("text", "simbad_main_id"),
        ("num", "simbad_nbref"),
        ("num", "simbad_sep_arcsec"),
        ("bool", "gaia_var_flag"),
        ("num", "gaia_var_score"),
        ("num", "gaia_eb_period"),
        ("text", "gaia_eb_morph"),
        ("num", "gaia_eb_global_ranking"),
        ("bool", "gaia_epoch_available"),
        ("num", "gaia_epoch_g_range"),
        ("num", "gaia_epoch_lc_g_range"),
        ("num", "gaia_epoch_lc_n_g"),
        ("text", "microlens_name"),
        ("text", "microlens_alt_name"),
        ("num", "microlens_te_days"),
        ("num", "microlens_sep_arcsec"),
        ("num", "ztf_var_period"),
        ("num", "ztf_var_amp"),
        ("text", "tns_name"),
        ("text", "tns_disc_date"),
        ("num", "tns_redshift"),
        ("text", "alerce_oid"),
        ("num", "alerce_ndet"),
        ("num", "alerce_lc_prob"),
        ("text", "alerce_stamp_class"),
        ("num", "alerce_stamp_prob"),
    ]),
    ("Candidate Context", [
        ("text", "timescale"),
        ("text", "source_id"),
        ("text", "gaia_id"),
        ("num", "ra"),
        ("num", "dec"),
        ("num", "phot_g_mean_mag"),
        ("num", "phot_bp_mean_mag"),
        ("num", "phot_rp_mean_mag"),
        ("num", "bp_rp"),
        ("num", "mg"),
        ("num", "mg0"),
        ("num", "bprp0"),
        ("num", "jd_first"),
        ("num", "jd_last"),
    ]),
    ("Nuclear Context", [
        ("num", "gaia_parallax_snr"),
        ("num", "gaia_pm_snr"),
        ("num", "gaia_stellar_veto_score"),
        ("num", "gaia_extragalactic_prior_score"),
        ("bool", "host_match"),
        ("text", "host_source"),
        ("num", "host_sep_arcsec"),
        ("num", "nuclear_offset_arcsec"),
        ("num", "host_nuclear_score"),
        ("select", "host_assoc_status"),
        ("bool", "radio_det"),
        ("text", "radio_source_catalogs"),
        ("num", "radio_sep_arcsec"),
        ("num", "radio_flux_mjy"),
        ("num", "radio_agn_prior_score"),
        ("num", "wise_agn_score"),
        ("num", "neowise_variability_score"),
        ("num", "xray_agn_prior_score"),
        ("num", "uv_tde_score"),
        ("num", "agn_prior_score"),
        ("text", "agn_prior_reasons"),
        ("num", "tde_candidate_score"),
        ("text", "tde_candidate_reasons"),
        ("num", "clagn_photometric_score"),
        ("text", "clagn_reasons"),
        ("num", "redshift"),
        ("select", "redshift_source"),
        ("text", "spectral_type"),
        ("select", "spectral_type_source"),
        ("select", "host_spectral_class"),
        ("bool", "prior_agn_spectrum_flag"),
        ("bool", "broad_line_flag"),
        ("text", "spectrum_sources"),
        ("text", "spectrum_links"),
        ("bool", "swift_uvot_obs"),
        ("bool", "swift_uvot_det"),
        ("bool", "swift_xrt_det"),
        ("num", "swift_uvot_sep_arcsec"),
        ("num", "swift_xrt_sep_arcsec"),
        ("text", "swift_source_catalogs"),
        ("select", "swift_status"),
        ("bool", "known_clagn_match"),
        ("text", "known_clagn_source"),
        ("text", "known_clagn_type"),
        ("text", "known_clagn_name"),
        ("num", "known_clagn_sep_arcsec"),
        ("select", "known_clagn_training_label"),
        ("num", "nuc_n_points"),
        ("num", "nuc_time_span_days"),
        ("num", "nuc_flux_frac_amp_p95_p05"),
        ("num", "nuc_flux_slope_snr"),
        ("num", "n_flare_events"),
        ("num", "recurrence_count"),
        ("num", "preflare_rms"),
        ("num", "tde_single_flare_score"),
        ("num", "tde_quiet_baseline_score"),
        ("num", "tde_no_recurrence_score"),
        ("num", "tde_smooth_decline_score"),
        ("num", "fallback_fit_r2"),
        ("num", "clagn_state_change_mag"),
        ("num", "clagn_monotonicity_score"),
        ("num", "clagn_plateau_score"),
        ("select", "lc_feature_status"),
    ]),
    ("LTV", [
        ("num", "ltv_slope"),
        ("num", "ltv_slope_quad"),
        ("num", "ltv_dispersion"),
        ("num", "ltv_median"),
        ("num", "ltv_median_err"),
        ("num", "ltv_max_diff"),
        ("num", "ltv_n_seasons"),
        ("num", "time_span_days"),
        ("num", "n_unique_nights"),
        ("num", "ltv_ls_period"),
        ("num", "ltv_ls_power"),
        ("num", "ltv_ls_fap"),
        ("bool", "ltv_vg_has_v"),
        ("num", "ltv_vg_overlap_days"),
        ("num", "ltv_vg_overlap_fraction"),
        ("num", "ltv_neowise_w1_slope"),
        ("num", "ltv_neowise_w1_w2_slope"),
        ("num", "ltv_neowise_n_epochs"),
        ("text", "filter_reason"),
        ("text", "ltv_class"),
        ("text", "ltv_class_reason"),
        ("num", "ltv_interest_score"),
        ("bool", "ltv_dust_candidate"),
        ("bool", "ltv_dust_excess"),
        ("bool", "ltv_vsx_match"),
        ("text", "ltv_vsx_name"),
        ("bool", "ltv_milliquas_match"),
        ("bool", "ltv_gaia_alert_match"),
    ]),
    ("LTV Season Diagnostics", [
        ("num", "ltv_season_points_min"),
        ("num", "ltv_season_points_median"),
        ("num", "ltv_season_points_max"),
        ("num", "ltv_season_span_days_mean"),
        ("num", "ltv_season_span_days_median"),
        ("num", "ltv_season_span_days_max"),
        ("num", "ltv_season_step_max_mag"),
        ("num", "ltv_season_step_mean_abs_mag"),
        ("num", "ltv_season_step_max_fraction"),
        ("num", "ltv_season_monotonicity_fraction"),
        ("num", "ltv_season_spearman_rho"),
        ("num", "ltv_season_kendall_tau"),
        ("num", "ltv_leave1out_slope_std"),
        ("num", "ltv_leave1out_slope_range"),
    ]),
    ("LTV Trend Diagnostics", [
        ("num", "ltv_coeff1"),
        ("num", "ltv_coeff2"),
        ("num", "ltv_trend_slope_mag_per_year"),
        ("num", "ltv_trend_quad_mag_per_year2"),
        ("num", "ltv_trend_slope_err_mag_per_year"),
        ("num", "ltv_trend_slope_snr"),
        ("num", "ltv_trend_r2"),
        ("num", "ltv_trend_delta_bic_linear"),
        ("num", "ltv_trend_delta_bic_quadratic"),
    ]),
    ("LTV Long-Term Features", [
        ("num", "ltv_smooth_p95_p5"),
        ("num", "ltv_smooth_var"),
        ("num", "ltv_resid_var"),
        ("num", "ltv_long_short_var_ratio"),
        ("num", "ltv_smooth_n_points"),
        ("num", "ltv_smooth_100d_p95_p5"),
        ("num", "ltv_smooth_100d_smooth_var"),
        ("num", "ltv_smooth_100d_resid_var"),
        ("num", "ltv_smooth_100d_long_short_var_ratio"),
        ("num", "ltv_smooth_100d_n_points"),
        ("num", "ltv_smooth_300d_p95_p5"),
        ("num", "ltv_smooth_300d_smooth_var"),
        ("num", "ltv_smooth_300d_resid_var"),
        ("num", "ltv_smooth_300d_long_short_var_ratio"),
        ("num", "ltv_smooth_300d_n_points"),
        ("num", "ltv_smooth_1000d_p95_p5"),
        ("num", "ltv_smooth_1000d_smooth_var"),
        ("num", "ltv_smooth_1000d_resid_var"),
        ("num", "ltv_smooth_1000d_long_short_var_ratio"),
        ("num", "ltv_smooth_1000d_n_points"),
        ("num", "ltv_binned_sf_n_bins"),
        ("num", "ltv_binned_sf_30d_mag2"),
        ("num", "ltv_binned_sf_100d_mag2"),
        ("num", "ltv_binned_sf_300d_mag2"),
        ("num", "ltv_binned_sf_1000d_mag2"),
        ("num", "ltv_binned_sf_3000d_mag2"),
        ("num", "ltv_binned_sf_300d_30d_ratio"),
        ("num", "ltv_binned_sf_1000d_30d_ratio"),
        ("num", "ltv_binned_sf_3000d_30d_ratio"),
        ("num", "ltv_binned_sf_slope"),
        ("num", "ltv_theil_sen_slope_mag_per_year"),
        ("num", "ltv_theil_sen_intercept_mag"),
        ("num", "ltv_theil_sen_low_slope_mag_per_year"),
        ("num", "ltv_theil_sen_high_slope_mag_per_year"),
        ("num", "ltv_bb_n_blocks"),
        ("num", "ltv_bb_n_change_points"),
        ("num", "ltv_bb_range_mag"),
        ("num", "ltv_bb_largest_jump_mag"),
        ("num", "ltv_bb_max_block_offset_mag"),
        ("num", "ltv_lowess_p95_p5"),
        ("num", "ltv_lowess_resid_std"),
        ("num", "ltv_lowess_max_abs_resid"),
        ("num", "ltv_variogram_short_mag2"),
        ("num", "ltv_variogram_mid_mag2"),
        ("num", "ltv_variogram_long_mag2"),
        ("num", "ltv_variogram_long_short_ratio"),
        ("num", "ltv_variogram_slope"),
    ]),
    ("LTV Stochastic", [
        ("num", "ltv_stoch_sf_ml_amplitude"),
        ("num", "ltv_stoch_sf_ml_gamma"),
        ("num", "ltv_stoch_iar_phi"),
        ("num", "ltv_stoch_mhps_high"),
        ("num", "ltv_stoch_mhps_low"),
        ("num", "ltv_stoch_mhps_non_zero"),
        ("bool", "ltv_stoch_mhps_pn_flag"),
        ("num", "ltv_stoch_mhps_ratio"),
        ("num", "ltv_stoch_gp_drw_sigma"),
        ("num", "ltv_stoch_gp_drw_tau"),
    ]),
    ("LTV Multi-Survey", [
        *[
            ("text" if kind == "text" else "bool" if kind == "bool" else "num", col)
            for col, _sql, kind in LTV_MS_FEATURE_COLUMN_SPECS
        ],
    ]),
    ("External Coverage", [
        ("num", "neowise_n_epochs"),
        ("num", "atlas_n_det_cyan"),
        ("num", "atlas_n_det_orange"),
        ("bool", "atlas_has_phot"),
        ("num", "atlas_cyan_range"),
        ("num", "atlas_orange_range"),
        ("num", "ztf_lc_n_det"),
        ("num", "ztf_lc_g_range"),
        ("num", "ztf_lc_r_range"),
        ("num", "gaia_epoch_n_obs"),
        ("num", "neowise_w1_range"),
        ("num", "neowise_w2_range"),
        ("num", "tess_n_sectors"),
        ("num", "tess_total_points"),
        ("num", "tess_flux_range"),
        ("num", "kepler_n_quarters"),
        ("num", "kepler_total_points"),
        ("num", "kepler_flux_range"),
        ("num", "aavso_lc_n_points"),
        ("num", "ogle_lc_n_points"),
        ("num", "ogle_lc_i_range"),
        ("num", "ogle_lc_v_range"),
        ("num", "stripe82_lc_n_points"),
        ("num", "stripe82_lc_u_range"),
        ("num", "stripe82_lc_g_range"),
        ("num", "stripe82_lc_r_range"),
        ("num", "stripe82_lc_i_range"),
        ("num", "stripe82_lc_z_range"),
        ("num", "allwise_mep_n_epochs"),
        ("num", "allwise_mep_w1_range"),
        ("num", "allwise_mep_w2_range"),
        ("num", "allwise_mep_w3_range"),
        ("num", "allwise_mep_w4_range"),
        ("num", "vvvx_virac_n_epochs"),
        ("num", "vvvx_virac_z_range"),
        ("num", "vvvx_virac_y_range"),
        ("num", "vvvx_virac_j_range"),
        ("num", "vvvx_virac_h_range"),
        ("num", "vvvx_virac_ks_range"),
        ("num", "ps1_lc_n_points"),
        ("num", "crts_lc_n_points"),
        ("bool", "xray_det"),
        ("num", "xray_flux"),
        ("num", "xray_sep_arcsec"),
    ]),
    ("General Flags", [
        ("bool", "catalog_match"),
        ("bool", "high_ruwe_flag"),
        ("bool", "periodic_flag"),
    ]),
    ("Periodicity", [
        ("bool", "lsp_is_alias"),
        ("bool", "lsp_is_significant"),
        ("num", "periodicity_score"),
        ("num", "periodicity_bootstrap_sig"),
        ("bool", "periodicity_is_significant"),
        ("num", "phase_quality_score"),
        ("num", "lsp_bootstrap_sig"),
        ("num", "lsp_power"),
        ("num", "lsp_period"),
        ("num", "pdm_theta"),
        ("num", "pdm_snr"),
        ("num", "pdm_bootstrap_sig"),
        ("bool", "pdm_is_significant"),
        ("num", "pdm_period"),
        ("num", "ce_entropy"),
        ("num", "ce_snr"),
        ("num", "ce_bootstrap_sig"),
        ("bool", "ce_is_significant"),
        ("num", "ce_period"),
        ("bool", "phase_plot_ready"),
        ("num", "phase_period_days"),
        ("text", "phase_source"),
    ]),
    ("Dip Detection", [
        ("bool", "dip_significant"),
        ("text", "dip_best_morph"),
        ("num", "dip_best_log_bf"),
        ("num", "dip_best_delta_bic"),
        ("num", "dip_best_width_param"),
        ("num", "dip_symmetry_score"),
        ("num", "dip_best_amp"),
        ("num", "dip_best_t0"),
        ("num", "dip_best_alpha"),
        ("num", "dip_best_tau"),
        ("num", "dip_bayes_factor"),
        ("num", "dip_best_p"),
        ("num", "dip_best_mag_event"),
        ("num", "dip_trigger_max"),
        ("num", "dip_max_event_prob"),
        ("num", "dip_trigger_threshold"),
    ]),
    ("Dip Runs", [
        ("num", "dip_count"),
        ("num", "dip_run_count"),
        ("num", "dip_max_run_points"),
        ("num", "dip_max_run_duration"),
        ("num", "dip_max_run_sum"),
        ("num", "dip_max_run_max"),
        ("num", "dip_max_run_cameras"),
        ("num", "dip_max_log_bf_local"),
    ]),
    ("Jump Detection", [
        ("bool", "jump_significant"),
        ("text", "jump_best_morph"),
        ("num", "jump_best_log_bf"),
        ("num", "jump_best_delta_bic"),
        ("num", "jump_best_width_param"),
        ("num", "jump_best_amp"),
        ("num", "jump_best_t0"),
        ("num", "jump_best_alpha"),
        ("num", "jump_best_tau"),
        ("num", "jump_bayes_factor"),
        ("num", "jump_best_p"),
        ("num", "jump_best_mag_event"),
        ("num", "jump_trigger_max"),
        ("num", "jump_max_event_prob"),
        ("num", "jump_trigger_threshold"),
    ]),
    ("Jump Runs", [
        ("num", "jump_count"),
        ("num", "jump_run_count"),
        ("num", "jump_max_run_points"),
        ("num", "jump_max_run_duration"),
        ("num", "jump_max_run_sum"),
        ("num", "jump_max_run_max"),
        ("num", "jump_max_run_cameras"),
        ("num", "jump_max_log_bf_local"),
    ]),
    ("Dip Recurrence", [
        ("bool", "dip_is_single_event"),
        ("num", "dip_inter_event_spacing_median"),
        ("num", "dip_inter_event_spacing_std"),
        ("num", "dip_amplitude_consistency"),
        ("num", "dip_duration_consistency"),
    ]),
    ("Jump Recurrence", [
        ("bool", "jump_is_single_event"),
        ("num", "jump_inter_event_spacing_median"),
        ("num", "jump_inter_event_spacing_std"),
        ("num", "jump_amplitude_consistency"),
        ("num", "jump_duration_consistency"),
    ]),
    ("Event Scoring", [
        ("num", "dipper_score"),
        ("num", "dipper_n_dips"),
        ("num", "dipper_n_valid_dips"),
        ("num", "jumper_score"),
        ("num", "jumper_n_jumps"),
        ("num", "jumper_n_valid_jumps"),
    ]),
    ("Stellar Parameters", [
        ("num", "ruwe"),
        ("num", "teff_gspphot"),
        ("num", "logg_gspphot"),
        ("num", "mh_gspphot"),
        ("num", "distance_gspphot"),
        ("num", "parallax"),
        ("num", "parallax_error"),
        ("num", "pmra"),
        ("num", "pmdec"),
        ("num", "radial_velocity"),
        ("num", "rv_amplitude_robust"),
    ]),
    ("Photometry", [
        ("num", "tmass_j"),
        ("num", "tmass_j_err"),
        ("num", "tmass_h"),
        ("num", "tmass_h_err"),
        ("num", "tmass_k"),
        ("num", "tmass_k_err"),
        ("num", "w1"),
        ("num", "w1_err"),
        ("num", "w2"),
        ("num", "w2_err"),
        ("num", "w3"),
        ("num", "w3_err"),
        ("num", "w4"),
        ("num", "w4_err"),
        ("num", "apass_b"),
        ("num", "apass_b_err"),
        ("num", "apass_g"),
        ("num", "apass_g_err"),
        ("num", "apass_r"),
        ("num", "apass_r_err"),
        ("num", "apass_i"),
        ("num", "apass_i_err"),
        ("num", "apass_v"),
        ("num", "apass_v_err"),
        ("num", "galex_fuv"),
        ("num", "galex_fuv_err"),
        ("num", "galex_nuv"),
        ("num", "galex_nuv_err"),
        ("num", "H_K"),
        ("num", "w1_w2"),
        ("num", "w1_w3"),
        ("num", "w1_w4"),
        ("num", "w2_w3"),
        ("num", "w2_w4"),
        ("num", "w3_w4"),
        ("num", "iphas_ha_mag"),
        ("num", "iphas_r_ha"),
        ("num", "iphas_ha_excess"),
        ("num", "vphas_ha_mag"),
        ("num", "vphas_r_ha"),
        ("num", "vphas_ha_excess"),
        ("num", "unwise_w1_zscore"),
        ("num", "unwise_w2_zscore"),
        ("bool", "unwise_w1_var"),
    ]),
    ("Derived Photometry", [
        ("num", "derived_bp_rp"),
        ("num", "derived_j_k"),
        ("num", "derived_mrp"),
        ("num", "derived_mks"),
        ("num", "derived_wrp"),
        ("num", "derived_wjk"),
    ]),
    ("Galactic Coordinates", [
        ("num", "gal_l"),
        ("num", "gal_b"),
    ]),
    ("Extinction & Environment", [
        ("text", "population"),
        ("text", "banyan_best_assoc"),
        ("num", "A_v_3d"),
        ("num", "ebv_3d"),
        ("num", "dust_sigma"),
        ("num", "age50"),
        ("num", "mass50"),
        ("num", "banyan_field_prob"),
    ]),
    ("Associations", [
        ("text", "sfr_name"),
        ("num", "sfr_sep_arcmin"),
        ("text", "cluster_name"),
        ("num", "cluster_dist_pc"),
        ("num", "cluster_membership_prob"),
    ]),
    ("Period Consensus", [
        ("text", "period_sources"),
        ("text", "period_primary_source"),
        ("text", "period_source_periods"),
        ("num", "period_n_sources"),
        ("num", "period_consensus_days"),
        ("num", "period_consensus_support"),
        ("bool", "period_consensus_agree"),
        ("bool", "period_ogle_match"),
        ("text", "period_ogle_name"),
        ("num", "period_ogle_days"),
        ("text", "period_ogle_class"),
        ("num", "period_ogle_sep_arcsec"),
    ]),
    ("LC Cadence & Coverage", [
        ("num", "stats_jd_start"),
        ("num", "stats_jd_end"),
        ("num", "stats_time_span_days"),
        ("num", "stats_n_unique_nights"),
        ("num", "stats_duty_cycle_fraction"),
        ("num", "stats_cadence_mean_dt_days"),
        ("num", "stats_cadence_median_dt_days"),
        ("num", "stats_cadence_p05_dt_days"),
        ("num", "stats_cadence_p95_dt_days"),
        ("num", "stats_file_points_total"),
        ("num", "stats_file_points_kept_after_filter"),
    ]),
    ("LC Photometric Scatter", [
        ("num", "stats_photometry_std_mag"),
        ("num", "stats_photometry_weighted_std_mag"),
        ("num", "stats_photometry_robust_sigma_mag"),
        ("num", "stats_photometry_IQR_mag"),
        ("num", "stats_camera_loo_corr_min"),
        ("num", "stats_camera_loo_corr_median"),
        ("num", "stats_camera_loo_rms_max"),
        ("num", "stats_photometry_mean_mag"),
        ("num", "stats_photometry_median_mag"),
        ("num", "stats_photometry_weighted_mean_mag"),
        ("num", "stats_photometry_weighted_mean_sem"),
        ("num", "stats_photometry_p05_mag"),
        ("num", "stats_photometry_p16_mag"),
        ("num", "stats_photometry_p84_mag"),
        ("num", "stats_photometry_p95_mag"),
        ("num", "stats_clipped_mean_mag_3sigma_about_median"),
        ("num", "stats_clipped_std_mag_3sigma_about_median"),
        ("num", "stats_n_outliers_removed_robust_3sigma"),
    ]),
    ("LC Variability", [
        ("num", "stats_variability_reduced_chi2_vs_constant"),
        ("num", "stats_variability_von_neumann_ratio"),
        ("num", "stats_variability_roms"),
        ("num", "stats_variability_lag1_autocorr"),
        ("num", "stats_variability_stetson_I"),
        ("num", "stats_variability_stetson_J"),
        ("num", "stats_variability_stetson_K"),
        ("num", "stats_variability_stetson_L"),
        ("num", "stats_variability_stetson_J_time"),
        ("num", "stats_variability_stetson_L_time"),
        ("num", "stats_variability_flux_asymmetry_m"),
        ("num", "stats_variability_quasi_periodicity_q"),
        ("num", "stats_variability_string_length_resid_total"),
        ("num", "stats_variability_string_length_resid_mean_step"),
        ("num", "stats_variability_string_length_resid_n_steps"),
        ("num", "stats_amplitude"),
        ("num", "stats_beyond_1_std"),
        ("num", "stats_con"),
        ("num", "stats_delta_mag_fid"),
        ("num", "stats_intrinsic_sigma_mag"),
        ("num", "stats_first_mag"),
        ("num", "stats_gskew"),
        ("num", "stats_max_slope"),
        ("num", "stats_meanvariance"),
        ("num", "stats_median_abs_dev"),
        ("num", "stats_median_brp"),
        ("num", "stats_percent_amplitude"),
        ("num", "stats_ahl_ratio"),
        ("num", "stats_q31"),
        ("num", "stats_skew"),
        ("num", "stats_small_kurtosis"),
        ("num", "stats_constancy_p_value"),
        ("num", "stats_anderson_darling"),
        ("num", "stats_pair_slope_trend"),
        ("num", "stats_rcs"),
        ("num", "stats_autocor_length"),
    ]),
    ("LC Period Search", [
        ("num", "stats_variability_lomb_scargle_best_period_days"),
        ("num", "stats_variability_lomb_scargle_peak_power"),
        ("num", "stats_variability_lomb_scargle_fap"),
        ("num", "stats_lafler_kinman_t_time"),
        ("num", "stats_lafler_kinman_t_phase"),
        ("num", "stats_lafler_kinman_delta"),
        ("num", "stats_window_alias_period_1"),
        ("num", "stats_window_alias_power_1"),
        ("num", "stats_window_alias_period_2"),
        ("num", "stats_window_alias_power_2"),
        ("num", "stats_window_alias_period_3"),
        ("num", "stats_window_alias_power_3"),
        ("num", "stats_window_alias_period_4"),
        ("num", "stats_window_alias_power_4"),
        ("num", "stats_window_alias_period_5"),
        ("num", "stats_window_alias_power_5"),
    ]),
    ("LC Structure Function", [
        ("num", "stats_sf_ml_amplitude"),
        ("num", "stats_sf_ml_gamma"),
    ]),
    ("LC Harmonics (folded)", [
        ("num", "stats_harmonics_order"),
        ("num", "stats_harmonics_period"),
        ("num", "stats_harmonics_a0"),
        ("num", "stats_harmonics_model_amplitude"),
        ("num", "stats_harmonics_reduced_chi2"),
        ("num", "stats_harmonics_mag_1"),
        ("num", "stats_harmonics_mag_2"),
        ("num", "stats_harmonics_mag_3"),
        ("num", "stats_harmonics_mag_4"),
        ("num", "stats_harmonics_mag_5"),
        ("num", "stats_harmonics_mag_6"),
        ("num", "stats_harmonics_mag_7"),
        ("num", "stats_harmonics_a1"),
        ("num", "stats_harmonics_a2"),
        ("num", "stats_harmonics_a3"),
        ("num", "stats_harmonics_a4"),
        ("num", "stats_harmonics_a5"),
        ("num", "stats_harmonics_a6"),
        ("num", "stats_harmonics_a7"),
        ("num", "stats_harmonics_b1"),
        ("num", "stats_harmonics_b2"),
        ("num", "stats_harmonics_b3"),
        ("num", "stats_harmonics_b4"),
        ("num", "stats_harmonics_b5"),
        ("num", "stats_harmonics_b6"),
        ("num", "stats_harmonics_b7"),
        ("num", "stats_harmonics_r21"),
        ("num", "stats_harmonics_r31"),
        ("num", "stats_harmonics_r41"),
        ("num", "stats_harmonics_r51"),
        ("num", "stats_harmonics_r61"),
        ("num", "stats_harmonics_r71"),
        ("num", "stats_harmonics_phase_2"),
        ("num", "stats_harmonics_phase_3"),
        ("num", "stats_harmonics_phase_4"),
        ("num", "stats_harmonics_phase_5"),
        ("num", "stats_harmonics_phase_6"),
        ("num", "stats_harmonics_phase_7"),
        ("num", "stats_harmonics_mse"),
        ("num", "stats_psi_cs"),
        ("num", "stats_psi_eta"),
        ("num", "stats_eb_rminima"),
        ("num", "stats_eb_primary_min_depth"),
        ("num", "stats_eb_secondary_min_depth"),
        ("num", "derived_harmonics_r32"),
        ("num", "derived_harmonics_r42"),
        ("num", "derived_harmonics_r43"),
        ("num", "derived_harmonics_a4_a2"),
        ("num", "derived_harmonics_b4_b2"),
    ]),
    ("LC Stochastic Models", [
        ("num", "stats_gp_drw_sigma"),
        ("num", "stats_gp_drw_tau"),
        ("num", "stats_iar_phi"),
        ("num", "stats_mhps_high"),
        ("num", "stats_mhps_low"),
        ("num", "stats_mhps_non_zero"),
        ("bool", "stats_mhps_pn_flag"),
        ("num", "stats_mhps_ratio"),
    ]),
    ("LC Error / SNR / Trend", [
        ("num", "stats_error_and_snr_stats_error_mean"),
        ("num", "stats_error_and_snr_stats_snr_median"),
        ("num", "stats_error_and_snr_stats_error_median"),
        ("num", "stats_error_and_snr_stats_error_p05"),
        ("num", "stats_error_and_snr_stats_error_p95"),
        ("num", "stats_error_and_snr_stats_snr_p05"),
        ("num", "stats_error_and_snr_stats_snr_p95"),
        ("num", "stats_trend_slope_mag_per_day"),
        ("num", "stats_trend_slope_mag_per_year"),
        ("num", "stats_trend_r2"),
    ]),
    ("Light Curve Basics", [
        ("text", "asas_sn_id"),
        ("text", "lc_path"),
        ("text", "baseline_source"),
        ("select", "pre_periodicity_label"),
        ("bool", "pre_periodic_flag"),
        ("num", "pre_periodicity_selected_period"),
        ("select", "pre_periodicity_method"),
        ("text", "trigger_mode"),
        ("text", "asassn_field_key"),
        ("text", "asassn_fields"),
        ("num", "asassn_field_count"),
        ("num", "asassn_field_key_fraction"),
        ("text", "camera_name_key"),
        ("text", "camera_names"),
        ("num", "camera_name_count"),
        ("num", "camera_name_key_fraction"),
        ("num", "n_points"),
        ("num", "n_cameras"),
        ("num", "baseline_mag"),
        ("num", "cadence_median_days"),
    ]),
    ("Classification", [
        ("text", "trigger_type"),
        ("text", "final_class"),
        ("num", "P_eb"),
        ("num", "P_cv"),
        ("num", "P_starspot"),
        ("num", "P_disk"),
        ("num", "a_circ_au"),
        ("num", "transit_prob"),
        ("num", "hill_radius_rsun"),
    ]),
    ("Multi-Survey Event", [
        ("text", "ms_feature_status"),
        ("text", "ms_feature_version"),
        ("text", "ms_event_type"),
        ("num", "ms_candidate_period_days"),
        ("num", "ms_event_start_jd"),
        ("num", "ms_event_end_jd"),
        ("num", "ms_event_t0_jd"),
        ("num", "ms_event_half_width_days"),
    ]),
    ("Multi-Survey ASAS-SN", [
        ("num", "ms_asassn_baseline_g_median"),
        ("num", "ms_asassn_baseline_v_median"),
        ("num", "ms_asassn_event_g_median"),
        ("num", "ms_asassn_event_v_median"),
        ("num", "ms_asassn_delta_g"),
        ("num", "ms_asassn_delta_v"),
        ("num", "ms_asassn_g_minus_v_baseline"),
        ("num", "ms_asassn_g_minus_v_event"),
        ("num", "ms_asassn_g_minus_v_delta"),
        ("num", "ms_asassn_n_baseline_g"),
        ("num", "ms_asassn_n_baseline_v"),
        ("num", "ms_asassn_n_event_g"),
        ("num", "ms_asassn_n_event_v"),
    ]),
    ("Multi-Survey Gaia", [
        ("bool", "ms_gaia_var_flag"),
        ("text", "ms_gaia_var_class"),
        ("num", "ms_gaia_var_score"),
        ("num", "ms_gaia_eb_period"),
        ("text", "ms_gaia_eb_morph"),
        ("num", "ms_gaia_eb_global_ranking"),
        ("num", "ms_gaia_eb_period_ratio"),
        ("num", "ms_gaia_epoch_g_baseline_median"),
        ("num", "ms_gaia_epoch_g_event_median"),
        ("num", "ms_gaia_epoch_g_delta"),
        ("num", "ms_gaia_epoch_n_baseline"),
        ("num", "ms_gaia_epoch_n_event"),
        ("num", "ms_radial_velocity"),
        ("num", "ms_rv_amplitude_robust"),
    ]),
    ("Multi-Survey NEOWISE", [
        ("num", "ms_neowise_w1_baseline_median"),
        ("num", "ms_neowise_w1_near_median"),
        ("num", "ms_neowise_w1_delta"),
        ("num", "ms_neowise_w2_baseline_median"),
        ("num", "ms_neowise_w2_near_median"),
        ("num", "ms_neowise_w2_delta"),
        ("num", "ms_neowise_w1_w2_baseline"),
        ("num", "ms_neowise_w1_w2_near"),
        ("num", "ms_neowise_w1_w2_delta"),
        ("num", "ms_neowise_n_baseline"),
        ("num", "ms_neowise_n_near"),
    ]),
    ("Multi-Survey TESS", [
        ("bool", "ms_tess_event_overlap"),
        ("num", "ms_tess_flux_baseline_median"),
        ("num", "ms_tess_flux_event_median"),
        ("num", "ms_tess_flux_frac_delta"),
        ("num", "ms_tess_half_depth_duration_days"),
        ("num", "ms_tess_ingress_slope_per_day"),
        ("num", "ms_tess_egress_slope_per_day"),
        ("num", "ms_tess_asymmetry"),
        ("num", "ms_tess_boxiness"),
        ("num", "ms_tess_n_baseline"),
        ("num", "ms_tess_n_event"),
    ]),
    ("Multi-Survey ZTF", [
        ("num", "ms_ztf_baseline_zg_median"),
        ("num", "ms_ztf_baseline_zr_median"),
        ("num", "ms_ztf_event_zg_median"),
        ("num", "ms_ztf_event_zr_median"),
        ("num", "ms_ztf_delta_zg"),
        ("num", "ms_ztf_delta_zr"),
        ("num", "ms_ztf_gr_baseline"),
        ("num", "ms_ztf_gr_event"),
        ("num", "ms_ztf_gr_delta"),
        ("num", "ms_ztf_gr_baseline_pairs"),
        ("num", "ms_ztf_gr_event_pairs"),
        ("num", "ms_ztf_n_baseline_zg"),
        ("num", "ms_ztf_n_baseline_zr"),
        ("num", "ms_ztf_n_event_zg"),
        ("num", "ms_ztf_n_event_zr"),
    ]),
    ("Fail Flags", [
        ("bool", "failed_any"),
        ("bool", "ltv_failed_slope"),
        ("bool", "ltv_failed_max_diff"),
        ("bool", "ltv_failed_dec"),
        ("bool", "ltv_failed_refcat_offset"),
        ("bool", "ltv_failed_photometric_scatter"),
        ("bool", "ltv_failed_high_pm"),
        ("bool", "ltv_failed_neighbor_high_pm"),
        ("bool", "ltv_failed_crowding"),
        ("bool", "failed_periodic_catalog"),
        ("bool", "failed_gaia_ruwe"),
        ("bool", "period_conflict_flag"),
        ("bool", "failed_posterior_strength"),
        ("bool", "failed_run_robustness"),
        ("bool", "failed_morphology"),
        ("bool", "failed_score"),
        ("bool", "failed_periodicity"),
        ("bool", "failed_signal_amplitude"),
        ("bool", "bad_cameras_filtered"),
    ]),
]
