from __future__ import annotations


SPECIAL_FILTERS = {
    "only_unreviewed": "Only unreviewed",
    "require_failed_any_false": "Require failed_any=False",
}

# Definite catalog/type hits that indicate an already-known object.
# Keep uncertainty-style vetting flags (PM diagnostics, broad YSO heuristics, etc.)
# out of this preset so the UI can apply only the hard known-type exclusions.
VETTING_KNOWN_BOOL_FILTERS = (
    "vetting_likely_known",
    "microlens_match",
)

VETTING_KNOWN_SELECT_FILTERS = (
    "vsx_class",
    "microlens_catalog",
    "asassn_var_type",
    "gaia_var_class",
    "simbad_otype",
    "ztf_var_type",
    "tns_type",
    "alerce_lc_class",
)


SIDEBAR_GROUPS = [
    ("Vetting", [
        ("bool", "vetting_likely_known"),
        ("bool", "microlens_match"),
        ("num", "pm_cluster_offset_sigma"),
        ("num", "pm_total"),
        ("bool", "high_pm_flag"),
        ("select", "vsx_class"),
        ("select", "microlens_catalog"),
        ("select", "asassn_var_type"),
        ("select", "gaia_var_class"),
        ("select", "simbad_otype"),
        ("select", "ztf_var_type"),
        ("select", "tns_type"),
        ("select", "alerce_lc_class"),
        ("select", "yso_class"),
    ]),
    ("LTV", [
        ("num", "ltv_slope"),
        ("num", "ltv_slope_quad"),
        ("num", "ltv_dispersion"),
        ("num", "ltv_median"),
        ("num", "ltv_median_err"),
        ("num", "ltv_max_diff"),
        ("num", "ltv_n_seasons"),
        ("num", "ltv_time_span_days"),
        ("num", "ltv_n_unique_nights"),
        ("num", "ltv_ls_period"),
        ("num", "ltv_ls_power"),
        ("num", "ltv_ls_fap"),
        ("bool", "ltv_vg_has_v"),
        ("num", "ltv_vg_overlap_days"),
        ("num", "ltv_vg_overlap_fraction"),
        ("num", "ltv_neowise_w1_slope"),
        ("num", "ltv_neowise_w1_w2_slope"),
        ("num", "ltv_neowise_n_epochs"),
        ("bool", "ltv_passed_filters"),
        ("bool", "ltv_dust_candidate"),
        ("bool", "ltv_dust_excess"),
        ("bool", "ltv_vsx_match"),
        ("bool", "ltv_milliquas_match"),
        ("bool", "ltv_gaia_alert_match"),
    ]),
    ("LTV Season Diagnostics", [
        ("num", "ltv_season_points_min"),
        ("num", "ltv_season_points_median"),
        ("num", "ltv_season_points_max"),
        ("num", "ltv_season_span_days_mean"),
        ("num", "ltv_season_span_days_median"),
        ("num", "ltv_season_span_days_max"),
        ("num", "ltv_season_step_max_mag"),
        ("num", "ltv_season_step_mean_abs_mag"),
        ("num", "ltv_season_step_max_fraction"),
        ("num", "ltv_season_monotonicity_fraction"),
        ("num", "ltv_season_spearman_rho"),
        ("num", "ltv_season_kendall_tau"),
        ("num", "ltv_leave1out_slope_std"),
        ("num", "ltv_leave1out_slope_range"),
    ]),
    ("LTV Trend Diagnostics", [
        ("num", "ltv_coeff1"),
        ("num", "ltv_coeff2"),
        ("num", "ltv_trend_slope_mag_per_year"),
        ("num", "ltv_trend_quad_mag_per_year2"),
        ("num", "ltv_trend_slope_err_mag_per_year"),
        ("num", "ltv_trend_slope_snr"),
        ("num", "ltv_trend_r2"),
        ("num", "ltv_trend_delta_bic_linear"),
        ("num", "ltv_trend_delta_bic_quadratic"),
    ]),
    ("LTV Stochastic", [
        ("num", "ltv_stoch_sf_ml_amplitude"),
        ("num", "ltv_stoch_sf_ml_gamma"),
        ("num", "ltv_stoch_iar_phi"),
        ("num", "ltv_stoch_mhps_high"),
        ("num", "ltv_stoch_mhps_low"),
        ("num", "ltv_stoch_mhps_non_zero"),
        ("bool", "ltv_stoch_mhps_pn_flag"),
        ("num", "ltv_stoch_mhps_ratio"),
        ("num", "ltv_stoch_gp_drw_sigma"),
        ("num", "ltv_stoch_gp_drw_tau"),
    ]),
    ("External Coverage", [
        ("num", "neowise_n_epochs"),
        ("num", "atlas_n_det_cyan"),
        ("num", "atlas_n_det_orange"),
        ("num", "gaia_epoch_n_obs"),
        ("num", "xray_flux"),
    ]),
    ("General Flags", [
        ("bool", "catalog_match"),
        ("bool", "high_ruwe_flag"),
    ]),
    ("Periodicity", [
        ("bool", "lsp_is_alias"),
        ("bool", "lsp_is_significant"),
        ("num", "periodicity_score"),
        ("num", "periodicity_bootstrap_sig"),
        ("bool", "periodicity_is_significant"),
        ("num", "phase_quality_score"),
        ("num", "lsp_bootstrap_sig"),
        ("num", "lsp_power"),
        ("num", "lsp_period"),
        ("num", "pdm_theta"),
        ("num", "pdm_snr"),
        ("num", "pdm_bootstrap_sig"),
        ("bool", "pdm_is_significant"),
        ("num", "ce_entropy"),
        ("num", "ce_snr"),
        ("num", "ce_bootstrap_sig"),
        ("bool", "ce_is_significant"),
    ]),
    ("Dip Detection", [
        ("bool", "dip_significant"),
        ("text", "dip_best_morph"),
        ("num", "dip_best_log_bf"),
        ("num", "dip_best_delta_bic"),
        ("num", "dip_best_width_param"),
        ("num", "dip_symmetry_score"),
        ("num", "dip_best_amp"),
        ("num", "dip_best_t0"),
        ("num", "dip_best_alpha"),
        ("num", "dip_best_tau"),
        ("num", "dip_bayes_factor"),
        ("num", "dip_best_p"),
        ("num", "dip_best_mag_event"),
        ("num", "dip_trigger_max"),
        ("num", "dip_max_event_prob"),
        ("num", "dip_trigger_threshold"),
    ]),
    ("Dip Runs", [
        ("num", "dip_count"),
        ("num", "dip_run_count"),
        ("num", "dip_max_run_points"),
        ("num", "dip_max_run_duration"),
        ("num", "dip_max_run_sum"),
        ("num", "dip_max_run_max"),
        ("num", "dip_max_run_cameras"),
        ("num", "dip_max_log_bf_local"),
    ]),
    ("Jump Detection", [
        ("bool", "jump_significant"),
        ("text", "jump_best_morph"),
        ("num", "jump_best_log_bf"),
        ("num", "jump_best_delta_bic"),
        ("num", "jump_best_width_param"),
        ("num", "jump_best_amp"),
        ("num", "jump_best_t0"),
        ("num", "jump_best_alpha"),
        ("num", "jump_best_tau"),
        ("num", "jump_bayes_factor"),
        ("num", "jump_best_p"),
        ("num", "jump_best_mag_event"),
        ("num", "jump_trigger_max"),
        ("num", "jump_max_event_prob"),
        ("num", "jump_trigger_threshold"),
    ]),
    ("Jump Runs", [
        ("num", "jump_count"),
        ("num", "jump_run_count"),
        ("num", "jump_max_run_points"),
        ("num", "jump_max_run_duration"),
        ("num", "jump_max_run_sum"),
        ("num", "jump_max_run_max"),
        ("num", "jump_max_run_cameras"),
        ("num", "jump_max_log_bf_local"),
    ]),
    ("Dip Recurrence", [
        ("bool", "dip_is_single_event"),
        ("num", "dip_inter_event_spacing_median"),
        ("num", "dip_inter_event_spacing_std"),
        ("num", "dip_amplitude_consistency"),
        ("num", "dip_duration_consistency"),
    ]),
    ("Jump Recurrence", [
        ("bool", "jump_is_single_event"),
        ("num", "jump_inter_event_spacing_median"),
        ("num", "jump_inter_event_spacing_std"),
        ("num", "jump_amplitude_consistency"),
        ("num", "jump_duration_consistency"),
    ]),
    ("Event Scoring", [
        ("num", "dipper_score"),
        ("num", "dipper_n_dips"),
        ("num", "dipper_n_valid_dips"),
        ("num", "jumper_score"),
        ("num", "jumper_n_jumps"),
        ("num", "jumper_n_valid_jumps"),
    ]),
    ("Stellar Parameters", [
        ("num", "ruwe"),
        ("num", "teff_gspphot"),
        ("num", "logg_gspphot"),
        ("num", "mh_gspphot"),
        ("num", "distance_gspphot"),
        ("num", "parallax"),
        ("num", "pmra"),
        ("num", "pmdec"),
    ]),
    ("Photometry", [
        ("num", "tmass_j"),
        ("num", "tmass_h"),
        ("num", "tmass_k"),
        ("num", "unwise_w1"),
        ("num", "unwise_w2"),
        ("num", "H_K"),
        ("num", "W1_W2"),
        ("num", "iphas_ha_mag"),
        ("num", "unwise_w1_zscore"),
        ("num", "unwise_w2_zscore"),
    ]),
    ("Galactic Coordinates", [
        ("num", "gal_l"),
        ("num", "gal_b"),
    ]),
    ("Extinction & Environment", [
        ("text", "population"),
        ("text", "banyan_best_assoc"),
        ("num", "A_v_3d"),
        ("num", "ebv_3d"),
        ("num", "age50"),
        ("num", "mass50"),
        ("num", "banyan_field_prob"),
    ]),
    ("Associations", [
        ("text", "sfr_name"),
        ("num", "sfr_sep_arcmin"),
        ("text", "cluster_name"),
        ("num", "cluster_membership_prob"),
    ]),
    ("Period Consensus", [
        ("num", "period_n_sources"),
        ("num", "period_consensus_days"),
        ("num", "period_consensus_support"),
        ("bool", "period_consensus_agree"),
    ]),
    ("LC Cadence & Coverage", [
        ("num", "stats_jd_start"),
        ("num", "stats_jd_end"),
        ("num", "stats_time_span_days"),
        ("num", "stats_n_unique_nights"),
        ("num", "stats_duty_cycle_fraction"),
        ("num", "stats_cadence_mean_dt_days"),
        ("num", "stats_cadence_median_dt_days"),
        ("num", "stats_cadence_p05_dt_days"),
        ("num", "stats_cadence_p95_dt_days"),
        ("num", "stats_file_points_total"),
        ("num", "stats_file_points_kept_after_filter"),
    ]),
    ("LC Photometric Scatter", [
        ("num", "stats_photometry_std_mag"),
        ("num", "stats_photometry_weighted_std_mag"),
        ("num", "stats_photometry_robust_sigma_mag"),
        ("num", "stats_photometry_IQR_mag"),
        ("num", "stats_photometry_mean_mag"),
        ("num", "stats_photometry_median_mag"),
        ("num", "stats_photometry_weighted_mean_mag"),
        ("num", "stats_photometry_weighted_mean_sem"),
        ("num", "stats_photometry_p05_mag"),
        ("num", "stats_photometry_p16_mag"),
        ("num", "stats_photometry_p84_mag"),
        ("num", "stats_photometry_p95_mag"),
        ("num", "stats_clipped_mean_mag_3sigma_about_median"),
        ("num", "stats_clipped_std_mag_3sigma_about_median"),
        ("num", "stats_n_outliers_removed_robust_3sigma"),
    ]),
    ("LC Variability", [
        ("num", "stats_variability_reduced_chi2_vs_constant"),
        ("num", "stats_variability_von_neumann_ratio"),
        ("num", "stats_variability_roms"),
        ("num", "stats_variability_lag1_autocorr"),
        ("num", "stats_variability_stetson_I"),
        ("num", "stats_variability_stetson_J"),
        ("num", "stats_variability_stetson_K"),
        ("num", "stats_variability_stetson_L"),
        ("num", "stats_variability_stetson_J_time"),
        ("num", "stats_variability_stetson_L_time"),
        ("num", "stats_variability_string_length_resid_total"),
        ("num", "stats_variability_string_length_resid_mean_step"),
        ("num", "stats_variability_string_length_resid_n_steps"),
        ("num", "stats_amplitude"),
        ("num", "stats_beyond_1_std"),
        ("num", "stats_con"),
        ("num", "stats_delta_mag_fid"),
        ("num", "stats_intrinsic_sigma_mag"),
        ("num", "stats_first_mag"),
        ("num", "stats_gskew"),
        ("num", "stats_max_slope"),
        ("num", "stats_meanvariance"),
        ("num", "stats_median_abs_dev"),
        ("num", "stats_median_brp"),
        ("num", "stats_percent_amplitude"),
        ("num", "stats_q31"),
        ("num", "stats_skew"),
        ("num", "stats_small_kurtosis"),
        ("num", "stats_constancy_p_value"),
        ("num", "stats_anderson_darling"),
        ("num", "stats_pair_slope_trend"),
        ("num", "stats_rcs"),
        ("num", "stats_autocor_length"),
    ]),
    ("LC Period Search", [
        ("num", "stats_variability_lomb_scargle_best_period_days"),
        ("num", "stats_variability_lomb_scargle_peak_power"),
        ("num", "stats_variability_lomb_scargle_fap"),
    ]),
    ("LC Structure Function", [
        ("num", "stats_sf_ml_amplitude"),
        ("num", "stats_sf_ml_gamma"),
    ]),
    ("LC Harmonics (folded)", [
        ("num", "stats_harmonics_order"),
        ("num", "stats_harmonics_period"),
        ("num", "stats_harmonics_a0"),
        ("num", "stats_harmonics_model_amplitude"),
        ("num", "stats_harmonics_reduced_chi2"),
        ("num", "stats_harmonics_mag_1"),
        ("num", "stats_harmonics_mag_2"),
        ("num", "stats_harmonics_mag_3"),
        ("num", "stats_harmonics_mag_4"),
        ("num", "stats_harmonics_mag_5"),
        ("num", "stats_harmonics_mag_6"),
        ("num", "stats_harmonics_mag_7"),
        ("num", "stats_harmonics_r21"),
        ("num", "stats_harmonics_r31"),
        ("num", "stats_harmonics_r41"),
        ("num", "stats_harmonics_r51"),
        ("num", "stats_harmonics_r61"),
        ("num", "stats_harmonics_r71"),
        ("num", "stats_harmonics_phase_2"),
        ("num", "stats_harmonics_phase_3"),
        ("num", "stats_harmonics_phase_4"),
        ("num", "stats_harmonics_phase_5"),
        ("num", "stats_harmonics_phase_6"),
        ("num", "stats_harmonics_phase_7"),
        ("num", "stats_harmonics_mse"),
        ("num", "stats_psi_cs"),
        ("num", "stats_psi_eta"),
    ]),
    ("LC Stochastic Models", [
        ("num", "stats_gp_drw_sigma"),
        ("num", "stats_gp_drw_tau"),
        ("num", "stats_iar_phi"),
        ("num", "stats_mhps_high"),
        ("num", "stats_mhps_low"),
        ("num", "stats_mhps_non_zero"),
        ("bool", "stats_mhps_pn_flag"),
        ("num", "stats_mhps_ratio"),
    ]),
    ("LC Error / SNR / Trend", [
        ("num", "stats_error_and_snr_stats_error_mean"),
        ("num", "stats_error_and_snr_stats_snr_median"),
        ("num", "stats_error_and_snr_stats_error_median"),
        ("num", "stats_error_and_snr_stats_error_p05"),
        ("num", "stats_error_and_snr_stats_error_p95"),
        ("num", "stats_error_and_snr_stats_snr_p05"),
        ("num", "stats_error_and_snr_stats_snr_p95"),
        ("num", "stats_trend_slope_mag_per_day"),
        ("num", "stats_trend_slope_mag_per_year"),
        ("num", "stats_trend_r2"),
    ]),
    ("Light Curve Basics", [
        ("text", "baseline_source"),
        ("text", "trigger_mode"),
        ("num", "n_points"),
        ("num", "n_cameras"),
        ("num", "baseline_mag"),
        ("num", "cadence_median_days"),
    ]),
    ("Classification", [
        ("text", "trigger_type"),
        ("text", "yso_class"),
        ("text", "final_class"),
        ("num", "P_eb"),
        ("num", "P_cv"),
        ("num", "P_starspot"),
        ("num", "P_disk"),
        ("num", "a_circ_au"),
        ("num", "transit_prob"),
        ("num", "hill_radius_rsun"),
    ]),
    ("Fail Flags", [
        ("bool", "failed_any"),
        ("bool", "period_conflict_flag"),
        ("bool", "failed_posterior_strength"),
        ("bool", "failed_run_robustness"),
        ("bool", "failed_morphology"),
        ("bool", "failed_score"),
        ("bool", "failed_periodicity"),
        ("bool", "failed_signal_amplitude"),
        ("bool", "bad_cameras_filtered"),
    ]),
]
