"""LTV settings: slope/diff/PM/crowding/EB/dust/NEOWISE/Gaia epoch/CMD defaults."""

# LTV filter thresholds
LTV_MIN_SLOPE = 0.03
LTV_MIN_DIFF = 0.3
LTV_MIN_DEC = -88.0
LTV_MAX_PM = 100.0
LTV_MAX_REDUCED_CHI2 = 5.0
LTV_MAX_EB_PERIOD_DAYS = 100.0
LTV_MIN_LS_POWER = 0.3
LTV_MAX_LS_FAP = 0.01
LTV_MAX_CROWDING_COUNT = 20

# LTV crossmatch
LTV_MATCH_RADIUS_ARCSEC = 3.0
VIZIER_TAP_URL = "https://tapvizier.cds.unistra.fr/TAPVizieR/tap"
SIMBAD_TAP_URL = "https://simbad.cds.unistra.fr/simbad/sim-tap"

# LTV workers / chunking
LTV_WORKERS = 10
LTV_CHUNK_SIZE = 10000
LTV_GAIA_CHUNK_SIZE = 1000
LTV_CROSSMATCH_CHUNK_SIZE = 1000

# LTV core
LTV_DSPRING = 2460023.5
LTV_MAX_SEASONS = 12
LTV_MIN_POINTS_PER_SEASON = 1
LTV_MIN_SEASONS_FOR_QUADRATIC = 3
LTV_CORE_CHUNK_SIZE = 10000

# LTV Lomb-Scargle
LTV_LS_MIN_PERIOD_DAYS = 10.0
LTV_LS_MAX_PERIOD_DAYS = 1000.0
LTV_LS_FAP_THRESHOLD = 0.1
LTV_LS_SAMPLES_PER_PEAK = 5

# LTV V/g overlap
LTV_MIN_OVERLAP_DAYS = 30.0
LTV_MIN_OVERLAP_FRACTION = 0.1

# LTV crowding
LTV_CROWDING_SEARCH_RADIUS_ARCSEC = 16.0

# REFCAT magnitude offset filter
LTV_MAX_REFCAT_OFFSET = 1.5

# Neighbor high-PM star filter
LTV_APERTURE_RADIUS_ARCSEC = 16.0
LTV_ASASSN_BASELINE_YEARS = 10.0
LTV_NEIGHBOR_FLUX_RATIO_LIMIT = 0.01
LTV_NEIGHBOR_SEARCH_RADIUS_ARCSEC = 120.0

# LTV dust flags
LTV_DUST_OPTICAL_SLOPE_THRESH = 0.03
LTV_DUST_COLOR_SLOPE_THRESH = 0.004
LTV_DUST_COLOR_EXCESS_THRESH = 0.3

# NEOWISE
NEOWISE_EPOCH_COMBINE_DAYS = 7.0
NEOWISE_MIN_SNR = 3.0
NEOWISE_RATE_LIMIT_SECONDS = 0.1
NEOWISE_MATCH_RADIUS_ARCSEC = 3.0

# Gaia epoch photometry
GAIA_EPOCH_DATA_RELEASE = "Gaia DR3"
GAIA_EPOCH_DATA_STRUCTURE = "RAW"
GAIA_EPOCH_RETRIEVAL_TYPE = "EPOCH_PHOTOMETRY"
GAIA_EPOCH_DELTA_MAG_THRESH = 0.5
GAIA_EPOCH_DELTA_COLOR_THRESH = 0.5

# CMD features
CMD_R_V = 3.1
CMD_A_G_PER_AV = 0.789
# Keep this consistent with the Gaia extinction coefficients used in
# characterize.py: A_BP / A_V = 1.002 and A_RP / A_V = 0.589.
CMD_E_BP_RP_PER_AV = 1.002 - 0.589
