"""Vetting settings: SIMBAD, ALeRCE, ATLAS, ZTF, TNS, eROSITA, NEOWISE query params."""

from datetime import datetime, timezone

# SIMBAD
VETTING_SIMBAD_BATCH_SIZE = 500
VETTING_SIMBAD_RETRY_DELAY = 5
VETTING_SIMBAD_MAX_RETRIES = 3

# API URLs
GAIA_ESA_TAP_URL = "https://gea.esac.esa.int/tap-server/tap"
ALERCE_API_BASE = "https://api.alerce.online"
ATLAS_API_BASE = "https://fallingstar-data.com/forcedphot"
TNS_API_BASE = "https://www.wis-tns.org/api"
IRSA_TAP_URL = "https://irsa.ipac.caltech.edu/TAP"


# Catalog identifiers
ASASSN_VAR_CATALOG_ID = "II/366/catv2021"
ZTF_VAR_CATALOG_ID = "J/ApJS/249/18/table2"
EROSITA_CATALOG_ID = "J/A+A/682/A34/erass1-m"
OGLE_MICROLENS_CATALOG_ID = "J/ApJS/244/29/table3"

# Crossmatch radii
ALERCE_RADIUS_ARCSEC = 3.0
ATLAS_MJD_MIN = 57000
ZTF_VAR_RADIUS_ARCSEC = 3.0
TNS_RADIUS_ARCSEC = 5.0
EROSITA_RADIUS_ARCSEC = 10.0
OGLE_MICROLENS_RADIUS_ARCSEC = 2.0
NEOWISE_VET_MAX_SEP_ARCSEC = 3.0
ZTF_LC_RADIUS_ARCSEC = 2.0
CRTS_MATCH_RADIUS_ARCSEC = 3.0

# Batch/worker sizes
ALERCE_BATCH_SIZE = 50
TNS_BATCH_SIZE = 50
ALERCE_WORKERS = 8
NEOWISE_VET_WORKERS = 4
CRTS_CHUNK_SIZE = 100
GAIA_EPOCH_VET_CHUNK_SIZE = 50

# ATLAS polling
ATLAS_POLL_INTERVAL = 10
ATLAS_MAX_POLL = 120

# HTTP
VETTING_HTTP_TIMEOUT = 60
VETTING_BACKOFF_CAP = 8
MICROLENS_OGLE_EWS_START_YEAR = 2011
MICROLENS_KMTNET_START_YEAR = 2016
MICROLENS_DEFAULT_END_YEAR = datetime.now(timezone.utc).year

# Misc
PANSTARRS_DEC_LIMIT = -30.5
TESS_SEARCH_RADIUS_ARCSEC = 21
AAVSO_MAX_PAGES = 50
AAVSO_RESULTS_PER_PAGE = 200
