"""Classification settings: EB/CV/starspot/YSO/disk thresholds + physical constants."""

# Physical constants
SOLAR_MASS_KG = 1.989e30
SOLAR_RADIUS_M = 6.957e8
AU_M = 1.496e11
DAY_S = 86400
GRAVITATIONAL_CONSTANT_SI = 6.674e-11
EARTH_MASS_KG = 5.972e24

# EB classification
EB_SHORT_DIP_DAYS = 10
EB_LONG_DIP_DAYS = 30
EB_SHORT_P = 0.3
EB_LONG_P = 0.05
EB_VERY_LONG_P = 0.01
EB_PERIODIC_BONUS = 0.4
EB_SYMMETRIC_BONUS = 0.2
EB_BINARY_BONUS = 0.3
EB_ASYMMETRY_THRESHOLD = 0.1

# CV classification
CV_BP_RP_THRESHOLD = 0.5
CV_G_ABS_THRESHOLD = 8
CV_BASE_P = 0.3
CV_HA_EW_THRESHOLD = 10
CV_HA_BONUS = 0.4
CV_KNOWN_P = 0.95

# Starspot classification
STARSPOT_SMALL_AMP = 0.05
STARSPOT_MEDIUM_AMP = 0.15
STARSPOT_SMALL_P = 0.4
STARSPOT_MEDIUM_P = 0.1
STARSPOT_LARGE_P = 0.01
STARSPOT_ROTATION_PERIOD_DAYS = 30

# YSO color cuts (Koenig & Leisawitz 2014)
YSO_CLASS_I_W1W2 = 0.8
YSO_CLASS_II_W1W2_MIN = 0.25
YSO_CLASS_II_HK = 0.3
YSO_DUST_CORRECTION_HK = 0.18
YSO_DUST_CORRECTION_W1W2 = 0.05

# Disk probability
DISK_BASE_P = 0.1
DISK_LARGE_A_AU = 2
DISK_VERY_LARGE_A_AU = 10
DISK_LARGE_A_P = 0.3
DISK_VERY_LARGE_A_P = 0.5
DISK_LARGE_HILL_BONUS = 0.1
DISK_NO_IR_EXCESS_BONUS = 0.1
DISK_P_CAP = 0.8

# Final classification thresholds
CLASSIFY_EB_THRESHOLD = 0.5
CLASSIFY_CV_THRESHOLD = 0.5
CLASSIFY_STARSPOT_THRESHOLD = 0.5
CLASSIFY_DISK_THRESHOLD = 0.4
CLASSIFY_MS_EB_REJECTION = 0.3
CLASSIFY_MS_CV_REJECTION = 0.3

# Query radii (classify-specific)
CLASSIFY_IPHAS_RADIUS_ARCSEC = 2.0
CLASSIFY_PS1_RADIUS_ARCSEC = 2.0
