"""Filter settings: tagging, post-filter, camera filter, LC cleaning thresholds."""

# Tagging
MIN_TIME_SPAN = 100.0
MIN_POINTS_PER_DAY = 0.05
MIN_CAMERAS = 2
VSX_MAX_SEP_ARCSEC = 3.0
VSX_MODE = "tag"
CAMERA_MEDIAN_TOLERANCE = 0.2
STATS_CHUNK_SIZE = 10000

# Pre-events periodicity gate
PRE_PERIODICITY_MIN_PERIOD = 0.2
PRE_PERIODICITY_MAX_PERIOD = 100.0
PRE_PERIODICITY_N_PERIODS = 5000
PRE_PERIODICITY_CE_SNR_THRESHOLD = 10.0
PRE_PERIODICITY_MIN_POINTS = 50
PRE_PERIODICITY_SCATTER_RATIO_MAX = 0.8

# Periodic-baseline residual search
PHASE_TEMPLATE_PHASE_BINS = 64
PHASE_TEMPLATE_PROFILE_SMOOTH_WINDOW = 5
PHASE_TEMPLATE_MIN_POINTS = 50

# Legacy periodic folded-profile branch settings kept for compatibility with
# older tooling; the main pipeline now uses the phase-template baseline.
PERIODIC_EVENTS_PHASE_BINS = PHASE_TEMPLATE_PHASE_BINS
PERIODIC_EVENTS_PROFILE_SMOOTH_WINDOW = PHASE_TEMPLATE_PROFILE_SMOOTH_WINDOW
PERIODIC_EVENTS_MIN_POINTS = PHASE_TEMPLATE_MIN_POINTS
PERIODIC_EVENTS_MIN_SUPPORT_POINTS = 12
PERIODIC_EVENTS_MIN_CYCLE_SUPPORT = 3
PERIODIC_EVENTS_MIN_CAMERA_SUPPORT = 2
PERIODIC_EVENTS_DEPTH_SNR_THRESHOLD = 4.0
PERIODIC_EVENTS_MAX_DIP_WIDTH_PHASE = 0.6

# Post-filter
MIN_BAYES_FACTOR = 10.0
POST_FILTER_MIN_RUN_CAMERAS = 2
POST_FILTER_MIN_RUN_POINTS = 2

# LC cleaning (utils.py)
CLEAN_LC_MAX_ERROR_ABSOLUTE = 1.0
CLEAN_LC_MAX_ERROR_SIGMA = 5.0

# Bad camera detection (utils.py)
BAD_CAMERA_WINDOW_DAYS = 100.0
BAD_CAMERA_MIN_OVERLAP_POINTS = 10
BAD_CAMERA_SCATTER_RATIO_THRESHOLD = 2.5
BAD_CAMERA_MIN_CAMERAS = 2
OFFSET_CAMERA_SIGMA_THRESHOLD = 15.0
CATASTROPHIC_MIN_POINTS_PER_CAMERA = 30
CATASTROPHIC_MAG_EXCURSION = 3.0
CATASTROPHIC_SUPPORT_WINDOW_DAYS = 2.0
CATASTROPHIC_SUPPORT_EXCURSION = 0.75
CATASTROPHIC_MAX_FRACTION = 0.03

# Post-filter validation defaults
POST_FILTER_MAX_RUWE = 1.4
POST_FILTER_MAX_PM = 100.0
POST_FILTER_MAX_SEP_ARCSEC = 3.0
POST_FILTER_REL_TOL = 0.10
POST_FILTER_MIN_DELTA_BIC = 10.0
POST_FILTER_MIN_DIP_SCORE = -3.0
POST_FILTER_MIN_JUMP_SCORE = -3.0
POST_FILTER_PDM_SNR_THRESHOLD = 5.0
POST_FILTER_CE_SNR_THRESHOLD = 5.0
POST_FILTER_PDM_METHOD = "plavchan"
POST_FILTER_PDM_MIN_THETA = 0.6
POST_FILTER_CE_MIN_ENTROPY = 0.6
POST_FILTER_PERIODICITY_SCORE = 99.0
POST_FILTER_CONSENSUS_MAD_FLOOR = 0.001
POST_FILTER_COORD_CHUNK_SIZE = 200000
