"""Statistics and periodogram settings: MAD, Lomb-Scargle, PDM, CE defaults."""

# MAD scale factor (normal distribution)
MAD_SCALE = 1.4826

# Lomb-Scargle defaults
LS_MIN_FREQUENCY = 1.0 / 365.25
LS_MAX_FREQUENCY = 10.0
LS_ALIAS_TOLERANCE = 0.1
LS_ALIAS_PERIODS = [1.0, 0.5, 29.53, 365.25, 182.625]

# PDM defaults
PDM_MIN_PERIOD = 0.1
PDM_MAX_PERIOD = 100.0
PDM_N_PERIODS = 10000
PDM_N_BINS = 20

# CE defaults
CE_N_PHASE_BINS = 20
CE_N_MAG_BINS = 10

# LS oversampling
LS_SAMPLES_PER_PEAK = 10

# Period-search local refinement (coarse global scan + local rescan)
PERIODOGRAM_REFINE_TOP_K = 5
PERIODOGRAM_REFINE_WINDOW_STEPS = 3.0
PERIODOGRAM_REFINE_N_GRID = 2001

# Bootstrap
BOOTSTRAP_MIN_POINTS = 50
BOOTSTRAP_SIGNIFICANCE = 0.01

# Misc analysis
CON_THRESHOLD = 2.0
PAIR_SLOPE_N_TAIL = 30
AUTOCORR_MAX_LAG = 100
STRUCTURE_FUNCTION_N_BINS = 20
FOURIER_N_HARMONICS = 7
DRW_MIN_POINTS = 20
IAR_MIN_POINTS = 10
MHPS_MIN_POINTS = 20
MHPS_SCALE_SHORT = 10.0
MHPS_SCALE_LONG = 100.0
SEASON_GAP_DAYS = 30.0
EXPOSURE_BIN_DAYS = 3.0
SNR_CONVERSION_FACTOR = 1.0857

# Single-band Stetson pairing window used for paper-style I/J/L.
STETSON_PAIR_MAX_DT_DAYS = 2.0

# FWHM conversion
FWHM_SIGMA_FACTOR = 2.3548
