"""Filter settings: pre-filter, post-filter, camera filter, LC cleaning thresholds."""

# Pre-filter
MIN_TIME_SPAN = 100.0
MIN_POINTS_PER_DAY = 0.05
MIN_CAMERAS = 2
VSX_MAX_SEP_ARCSEC = 3.0
VSX_MODE = "tag"
CAMERA_MEDIAN_TOLERANCE = 0.2
STATS_CHUNK_SIZE = 5000

# Post-filter
MIN_BAYES_FACTOR = 10.0
POST_FILTER_MIN_RUN_CAMERAS = 2
POST_FILTER_MIN_RUN_POINTS = 2

# LC cleaning (utils.py)
CLEAN_LC_MAX_ERROR_ABSOLUTE = 1.0
CLEAN_LC_MAX_ERROR_SIGMA = 5.0

# Bad camera detection (utils.py)
BAD_CAMERA_WINDOW_DAYS = 100.0
BAD_CAMERA_MIN_OVERLAP_POINTS = 10
BAD_CAMERA_SCATTER_RATIO_THRESHOLD = 2.5
BAD_CAMERA_MIN_CAMERAS = 2
OFFSET_CAMERA_SIGMA_THRESHOLD = 15.0
CATASTROPHIC_MIN_POINTS_PER_CAMERA = 30
CATASTROPHIC_MAG_EXCURSION = 3.0
CATASTROPHIC_SUPPORT_WINDOW_DAYS = 2.0
CATASTROPHIC_SUPPORT_EXCURSION = 0.75
CATASTROPHIC_MAX_FRACTION = 0.03
